FROM golang:latest as builder

LABEL repo-url="https://github.com/PabloGamiz/SafeEvents-Backend"
LABEL version="alpha"

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

#RUN go test ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main cmd/safe-events/main.go

######## Start a new stage from scratch #######
FROM alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/.env .
COPY --from=builder /app/main .

# Command to run the executable
CMD [ "./main" ]